### ISSUE TITLE
Code error/typo for Polymer at "Prop validate Object"

### ISSUE THREAD

**Issue by hormesiel** [jeffcarp/frontend-hyperpolyglot#25]
There's an error (or maybe just a typo) at line `Prop validate Object` for `Polymer`. It's written :

``` javascript
properties: {
  myObj: {type: Number}  
}
```

But it should be :

``` javascript
properties: {
  myObj: {type: Object}
}
```

Also I don't know if the author knows but it could be shortened to just :

``` javascript
properties: {
  myObj: Object
}
```

The four previous lines can be shortened to.

Very nice work btw. Very helpful.

**Comment by jeffcarp** [comment]
Thank you for catching that @flawyte! Will push a fix momentarily.
