### ISSUE TITLE
One way data binding in Angular 1

### ISSUE THREAD

**Issue by fadamakis** [jeffcarp/frontend-hyperpolyglot#6]
The correct syntax is       `<Child foo='::scope.bar' />`

https://docs.angularjs.org/guide/expression

**Comment by jeffcarp** [comment]
Thank you @fadamakis!

**Comment by jeffcarp** [comment]
Thinking about this more - I think this might require a new section. These are two distinct behaviors:
1. One-way data binding - where a parent's property is passed down but still updated
2. One-time data binding - where a parent's property is passed down once and never updated again (e.g. your example `<Child foo='::scope.bar' />`)
