### ISSUE TITLE
Angular 1.5.5 & Two-way binding (components)

### ISSUE THREAD

**Issue by gonzoyumo** [jeffcarp/frontend-hyperpolyglot#7]
Hi, 

great job for putting all of this together !

Though, there is a little oversight about Angular 1.5.5 
- Two-way binding (components)

``` html
<child foo="bar" />
```

cheers

**Comment by jeffcarp** [comment]
Awesome, thank you for catching that @gonzoyumo!

**Comment by jeffcarp** [comment]
Pushed as ae88eaf09c58096cf5f2baee427f4428a3e3ebaa
